//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrabajoPracticoWeb3.App_Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Sedes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sedes()
        {
            this.Carteleras = new HashSet<Carteleras>();
            this.Reservas = new HashSet<Reservas>();
        }
    
        public int IdSede { get; set; }
        [StringLength (40, MinimumLength =2 , ErrorMessage = "El minimo es 2 caracteres")]
        [Required(ErrorMessage = "¡Se necesita un Nombre!")]
        public string Nombre { get; set; }
        [StringLength(40, MinimumLength = 2, ErrorMessage = "El minimo es 2 caracteres")]
        [Required(ErrorMessage = "¡Se necesita una dirección!")]
        public string Direccion { get; set; }
        [StringLength(40, MinimumLength = 2, ErrorMessage = "El minimo es 2 caracteres")]
        [Required(ErrorMessage = "¡Se necesita un precio general!")]
        public decimal PrecioGeneral { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Carteleras> Carteleras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservas> Reservas { get; set; }
    }
}
